
CXX_FLAGS=-g -Wall -Werror -std=c++17

all: clean strplus strstream

strplus:
	clang++ -o strplus strplus.cc $(CXX_FLAGS)

strstream:
	clang++ -o strstream strstream.cc $(CXX_FLAGS)

clean:
	rm -f strplus strstream
